### PR TITLE
Stored all velocity (velocity, and p1 to p3) in a vector called velocity

### PR DESCRIPTION
**Pull request by CaroleAnneDaunais**

### CODE REVIEW

**Review by blaisb — COMMENTED** [review]
Very good first change!
The next step would be to remove the p1, p2, etc. variables and use a vector directly from the get go. Do you want to do this in this PR?

**Comment by CaroleAnneDaunais** [comment]
> Very good first change!
> The next step would be to remove the p1, p2, etc. variables and use a vector directly from the get go. Do you want to do this in this PR?

Yes definitely!

**Comment by blaisb** [comment]
Very cool & much cleaner.
I suggest that once CI pass I merge? @CaroleAnneDaunais

**Comment by CaroleAnneDaunais** [comment]
Yes I was waiting the the CI, it will be ready to merge!

**Pull request merged**
