### PR TITLE
Lethe Docker Image

### PR DESCRIPTION
**Pull request by technophil98**
# Description of the problem

Compiling Lethe along with its dependencies can be a tall order for newcomers who simply wants to experiment with the project.

# Description of the solution

This PR introduces Docker support for Lethe. It includes:

- A Dockerfile to build Lethe in a containerized environment
- A Docker workflow to automate Docker image build and push of master commits
- A custom entrypoint script to bridge the multiple executables/applications to a single `lethe` command
- Usage documentation

# How Has This Been Tested?

The workflow was tested with my personal fork of Lethe to avoid polluting the master branch. You can see the outcome here: https://github.com/technophil98/lethe/runs/4830391609. Don't look at the commit names; bad practices disappear when debugging automated processes...

I also tested the resulting image with the 2D Lid-Driven Cavity Flow example. Additional tests are welcomed since I don't understand how Lethe (or CFD in general) works; I need a _real_ engineer's help. 😅 

# Future changes

- Remove dependency for test in Dockerfile and root CMakeLists.txt
- Tune Docker cache parameters to avoid a 15 minutes build time

# Comments

The docker workflow **will** fail with the current configuration of the repo. GitHub somehow requires us to manually build and push the image before anyway Action workflow. We can be proactive and run these commands before merging:
```shell
docker build -t ghcr.io/lethe-cfd/lethe:lethe_docker_image .
docker push ghcr.io/lethe-cfd/lethe:lethe_docker_image
```
We can delete this temporary image tag after a proper execution of the docker workflow.

By default, Lethe weighs about 2 GB. It is caused by duplicated compiled library object data copied over every executable. I was able to slim down the Lethe part of the image down to 300 MB by compiling with shared-library CMake flags. The image still weighs about 3 GB because it is based on the 2.7 GB dealii image.

### CODE REVIEW

**Review by blaisb — APPROVED** [review]

**Comment by blaisb** [comment]
Really cool but I have a question, what do you mean by this comment?

> The docker workflow will fail with the current configuration of the repo. GitHub somehow requires us to manually build and push the image before anyway Action workflow. We can be proactive and run these commands before merging:

>docker build -t ghcr.io/lethe-cfd/lethe:lethe_docker_image .
>docker push ghcr.io/lethe-cfd/lethe:lethe_docker_image
>We can delete this temporary image tag after a proper execution of the docker workflow.

>By default, Lethe weighs about 2 GB. It is caused by duplicated compiled library object data copied over every executable. I was able to slim down the Lethe part of the image down to 300 MB by compiling with shared-library CMake flags. The image still weighs about 3 GB because it is based on the 2.7 GB dealii image.

**Comment by technophil98** [comment]
The workflow is configured to build the Docker image and push it immediately to the GitHub Packages Registry. I don't know why, but GitHub Action runners cannot push a certain package - in our case, the `lethe-cfd/lethe` image - if we don't [manually allow it to do so](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio). Even worse, we can't access a package's settings if it doesn't exist.

The (not so simple) solution:
- Build the image locally with a temporary tag like `ghcr.io/lethe-cfd/lethe:lethe_docker_image`
- Create a `packages:write` token and login with Docker [following this guide](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry).
- Push the image
- Manually add the [lethe-cfd/lethe](https://github.com/lethe-cfd/lethe) repo to the allowlist of the package with write permissions
- Merge this PR and hope it will push to the registry by its own
- Delete the `lethe_docker_image` version of the image
- Profit

I've done it on my personal fork, but don't have the necessary privileges to do it on the main repo.

**Comment by blaisb** [comment]
> The workflow is configured to build the Docker image and push it immediately to the GitHub Packages Registry. I don't know why, but GitHub Action runners cannot push a certain package - in our case, the `lethe-cfd/lethe` image - if we don't [manually allow it to do so](https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio). Even worse, we can't access a package's settings if it doesn't exist.
> 
> The (not so simple) solution:
> 
> * Build the image locally with a temporary tag like `ghcr.io/lethe-cfd/lethe:lethe_docker_image`
> * Create a `packages:write` token and login with Docker [following this guide](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry).
> * Push the image
> * Manually add the [lethe-cfd/lethe](https://github.com/lethe-cfd/lethe) repo to the allowlist of the package with write permissions
> * Merge this PR and hope it will push to the registry by its own
> * Delete the `lethe_docker_image` version of the image
> * Profit
> 
> I've done it on my personal fork, but don't have the necessary privileges to do it on the main repo.

Sounds legit. Maybe you can walk me through it later this week and we can do it together?

**Comment by technophil98** [comment]
> Sounds legit. Maybe you can walk me through it later this week and we can do it together?

All good 😄

**Pull request merged**
