### PR TITLE
Unique mesh reader

### LINKED ISSUE #561: Move mesh reading in DEM to the core grid utilities
Function `read_mesh()` in dem/read_mesh.cc is very similar to `attach_grid_to_triangulation()` in core/grids.cc.
It would be great to move the grid handling for DEM into the same file or rearrange functions in core/grids.cc to make it works for CFD and DEM meshes.

### PR DESCRIPTION
**Pull request by blaisb**
# Description of the problem

- The DEM module contained a lot of code duplication from the CFD module. The entire part related to the attachment of the grid to the triangulation was fully duplicated. This was a total mess.

# Description of the solution

- Refactor the reader to at least use the same attachment mechanism
- I also took the opportunity to clean the interface to use references instead of pointers. This make the code more portable and easier to use everywhere.

# How Has This Been Tested?

- All tests pass without a change

# Comments

- Ongoing process to clean the DEM code
- Closes #561

### CODE REVIEW

**Review by acdaigneault — COMMENTED** [review]
Yay, enfin :)! Will review tonight or tomorrow. 
I just want to say that you didn't modify the lines 172-188 in the cfd_dem_coupling.cc. I had some issues with that lately.

**Review by voferreira — APPROVED** [review]
I think it is good to go. It is way cleaner like this. The only thing I think could be changed, but it does not need to be within this PR is to use either "mesh" or "grid" for everything.

**Review by acdaigneault — APPROVED** [review]
All seems good to me! Useful changes :)
I was wondering why all related functions for grid were not moved in grids.cc (meaning removing dem/read_mesh.cc). I mean having like an overload function with the `Parameters::Lagrangian::BCDEM &bc_params` parameter.

**Comment by blaisb** [comment]
> All seems good to me! Useful changes :) I was wondering why all related functions for grid were not moved in grids.cc (meaning removing dem/read_mesh.cc). I mean having like an overload function with the `Parameters::Lagrangian::BCDEM &bc_params` parameter.

It's in my TODO, I just want to do it step by step with smaller PRs. The target is to eventually remove completely the Parameters::Lagrangian::BCDEM all together. In a next PR :).

**Pull request merged**
