### PR TITLE
Improve small scale rotating drum example

### PR DESCRIPTION
**Pull request by blaisb**
# Description of the problem

- The animation for the small scale rotating drum was very poor in term of temporal resolution and the results for the 18 rad/s did not make much sense. 
# Description of the solution

- I removed the 18 rad/s case and updated the animation on the youtube channel
- Indented the example
 

# How Has This Been Tested?

- Ran it on my machine to make the movie, significantly faster than before btw.

# Comments

- Trying to tidy up everythign
-

### CODE REVIEW

**Review by lpsaavedra — APPROVED** [review]
Seems good to me, nice video. There's one thing that was bothering me in the documentation and it is the appropriate indentation of the different parts of the prm file. I always thought it was so random, but I discovered today that the indentation needs to have only spaces and not tabs, because sphinx does not recognize tabs.  Replacing tabs by spaces should fix everything.

**Comment by blaisb** [comment]
> Seems good to me, nice video. There's one thing that was bothering me in the documentation and it is the appropriate indentation of the different parts of the prm file. I always thought it was so random, but I discovered today that the indentation needs to have only spaces and not tabs, because sphinx does not recognize tabs. Replacing tabs by spaces should fix everything.

let me try to remove all tabs for the file then :)

**Comment by lpsaavedra** [comment]
> let me try to remove all tabs for the file then :)
Perfect :) I might create a small PR removing all the tabs and fixing indentation of other examples sometime soon.

**Comment by blaisb** [comment]
> > let me try to remove all tabs for the file then :)
> 
> Perfect :) I might create a small PR removing all the tabs and fixing indentation of other examples sometime soon.

There is a nice tool for that in VS CODE:
https://marketplace.visualstudio.com/items?itemName=ilich8086.Untabify

**Pull request merged**
