### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by SGauvin**
CI tests!
I use a python script I found on github to check if the clang format is respected. It is in contrib/utilities. This script is great because its output is very clear on what lines need to be changed.

### CODE REVIEW

**Comment by SGauvin** [comment]
@blaisb 
My bad, the static check (clang format) failed.
I think you should check the webhooks, because we have travis.com and travis.org. Weird.

**Comment by blaisb** [comment]
> @blaisb
> My bad, the static check (clang format) failed.
> I think you should check the webhooks, because we have travis.com and travis.org. Weird.

Weird I did not see the merge request before you commented with my name on it. Weird stuff. Why did the last build fail ? Is it an indenting issue? Can you re-indent and commit/push again?

**Comment by blaisb** [comment]
> > @blaisb
> > My bad, the static check (clang format) failed.
> > I think you should check the webhooks, because we have travis.com and travis.org. Weird.
> 
> Weird I did not see the merge request before you commented with my name on it. Weird stuff. Why did the last build fail ? Is it an indenting issue? Can you re-indent and commit/push again?

@SGauvin I fixed the indentation error in the master branch so now everything appears to be ok. However, there seems to be one of the CI still that appears to be broken, but is it strictly the one related to the original pull request? I will wait for your input on that before going with the review. I think I will squash all your commits into a single beautiful merge ;)

**Comment by SGauvin** [comment]
> @SGauvin I fixed the indentation error in the master branch so now everything appears to be ok. However, there seems to be one of the CI still that appears to be broken, but is it strictly the one related to the original pull request? I will wait for your input on that before going with the review. I think I will squash all your commits into a single beautiful merge ;)

The test that failed ran three days ago and is the same indentation error that you just fixed. I don't know why the test on travis-ci.com re-ran, but the test on travis-ci.org didn't. I think you should remove travis-ci.org from lethe's weebhooks since travis is trying to move everyone to travis-ci.com.

**Comment by blaisb** [comment]
> > @SGauvin I fixed the indentation error in the master branch so now everything appears to be ok. However, there seems to be one of the CI still that appears to be broken, but is it strictly the one related to the original pull request? I will wait for your input on that before going with the review. I think I will squash all your commits into a single beautiful merge ;)
> 
> The test that failed ran three days ago and is the same indentation error that you just fixed. I don't know why the test on travis-ci.com re-ran, but the test on travis-ci.org didn't. I think you should remove travis-ci.org from lethe's weebhooks since travis is trying to move everyone to travis-ci.com.

Done.
I removed the webhook.
I'll squash and merge then.

**Comment by SGauvin** [comment]
Okay!
I'll be sure to squash my commits before doing a PR next time :)

**Comment by blaisb** [comment]
> Okay!
> I'll be sure to squash my commits before doing a PR next time :)

Don't worry about it. It's like the smallest thing to fix ;).
I'll do the review tomorrow most likely. Good job on this PR, this is marvelous stuff.

**Pull request merged**
