### PR TITLE
Sphinx Documentation

### PR DESCRIPTION
**Pull request by technophil98**
# Description of the problem

GitHub wikis are fine, but with a growing project like Lethe, their maintenance gets out of hand. Tracked documentation was needed alongside the code. This PR proposes a basic skeleton of a documentation system powered by Sphinx and automated with GitHub Actions.

# Description of the solution

image

Some pages of the Wiki were translated from Markdown to ReStructured Text (RST). Some improvements were made to use the additional features RST + Sphinx have to offer. Showcased in this basic documentation of Lethe showcases:

* Table of contents
* Images
* Code snippets
* Math equation
* Inline-math
* Handling of multiple documents spread across multiple files

# How Has This Been Tested?

See it for yourself! Unarchive this build artifact and open the `index.html` file on your browser. The generated webpages are available as a build artifact after a workflow run.

https://github.com/technophil98/lethe/suites/4791033385/artifacts/134053337

To build the doc:
```shell
cd doc
make html
```

# Future changes

* Automatic code documentation
* Lethe version injection in produced doc
* Animation support?
* PDF artifacts using LaTeX?
* PRM synthax highlighting for examples?
* Sky's the limit

# Comments

To me, the proposed theme is gorgeous! ✨
If you don't share the same opinion, you can go theme-shopping over there: https://sphinx-themes.org/

### CODE REVIEW

**Comment by technophil98** [comment]
Live (but outdated) demo:
https://technophil98.github.io/lethe/index.html

**Review by blaisb — APPROVED** [review]
Very good. I don't have anything to add. We will have some clean-up to do in the examples once this is set-up, but that's outside of the scope of this PR. Mission accomplished from my POV!

**Comment by blaisb** [comment]
@technophil98  Btw I tested the compilation of the Doc on my Manjaro machine and everything was smooth as hell. It could be good to add a "compiling the documentation" in the wiki though.

**Comment by technophil98** [comment]
> @technophil98 Btw I tested the compilation of the Doc on my Manjaro machine and everything was smooth as hell. It could be good to add a "compiling the documentation" in the wiki though.

In the GitHub wiki or in the documentation (that would be meta)?

**Comment by blaisb** [comment]
> > @technophil98 Btw I tested the compilation of the Doc on my Manjaro machine and everything was smooth as hell. It could be good to add a "compiling the documentation" in the wiki though.
> 
> In the GitHub wiki or in the documentation (that would be meta)?

Maybe in the documentation, since anyway the documentation will automatically be put online. It is meta as hell, but I love it. In the long term (e.g. a month) the wiki will be fully replaced by the sphinx doc.

**Comment by technophil98** [comment]
Done!

**Review by shahabgol — APPROVED** [review]
Very good work.

**Pull request merged**
