### PR TITLE
Constraints in Multigrid preconditioners

### PR DESCRIPTION
**Pull request by lpsaavedra**
# Description of the problem

The multigrid preconditioners were not supporting all the different constraints that are needed for the different problems in Lethe. 

# Description of the solution

Periodic and slip boundary conditions are now supported by both local smoothing and global coarsening. 

# How Has This Been Tested?

It has been tested by running simulations for several problems (poiseuille, flow around a sphere, tgv).

# Comments

The `merge_constraints` function used in LS is not available in deal.II v9.5. The bugs for the MGConstrainedDoFs object were fixed by @peterrum and me. They will be adjusted in two PRs in deal.II soon (https://github.com/dealii/dealii/pull/16161, https://github.com/dealii/dealii/pull/16164).

### CODE REVIEW

**Comment by blaisb** [comment]
@lpsaavedra seems you have one test failing in 9.5. If so, we can remove the 9.5 CI for Release and just keep the warning one and live with it. Just make sure you update the documentation to specify we really support 9.6pre right now and not really 9.5

**Comment by lpsaavedra** [comment]
I have now rebased, removed  the 9.5 CI for release and updated the documentation

**Comment by blaisb** [comment]
@lpsaavedra I think I can fix the CI for 9.5 my modifying the CMAKE. I'll take care of that Monday

**Review by blaisb — APPROVED** [review]

**Comment by blaisb** [comment]
@lpsaavedra I fixed 9.5 CI to keep working with your branch. I'll merge after CI

**Pull request merged**
