### PR TITLE
Migrate to clang format 16

### PR DESCRIPTION
**Pull request by blaisb**
# Description of the problem

- Deal.II uses clang format 16. It is important to maintain our clang format in a similar fashion that they do, for my sanity's sake.

# Description of the solution

- Migrate to clang format 16

# How Has This Been Tested?

- All tests should still pass. Barely any changes to files actually

### CODE REVIEW

**Review by hepap — CHANGES_REQUESTED** [review]
On my side indent and indent-all don't work. I think it is because the version was not updated in indent_common.sh at lines 42 and 59

**Comment by blaisb** [comment]
@hepap I fixed this, can you try again Hélène?

**Review by hepap — APPROVED** [review]
It's working now :)

**Comment by blaisb** [comment]
> It's working now :)

Yeah everything BUT the CI is working... I need to figure this out :)

**Comment by blaisb** [comment]
> > It's working now :)
> 
> Yeah everything BUT the CI is working... I need to figure this out :)

I figured it out, this current version should work. I had to rewrite the CI for the indent checking.

**Pull request merged**
